In [15]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

import sys, os
sys.path.append('../')

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [16]:
import numpy as np   
import pandas as pd
import pdb
import matplotlib.pyplot as plt
import scipy.stats as stats
import seaborn as sns
from tqdm import tqdm
import sys

from time import time
from largescale_smc.largescale_missingness import *
from largescale_smc.largescale_utils import *
from largescale_smc.largescale_method import *

In [17]:
from surprise import SVD, SVDpp
from surprise import accuracy

In [18]:
start_time = time()
#file_path = os.path.expanduser("../data/ml-100k/u.data")
file_path = os.path.expanduser("../data/ml-10m/ratings_no_timestamp.dat")
reader = DataReader(line_format="user item rating", sep="::")
splitter = DataSplitter(file_path, reader)

10000054it [00:15, 659998.30it/s]

Loaded 10000054 ratings from 69878 users and 10677 items.

In [19]:
train_samples, calib_samples, missing_idxs = splitter.sample_train_calib(k=5, random_state=0)
print(f"Elapsed time: {time()-start_time} seconds")

Elapsed time: 41.55747389793396 seconds

In [20]:
random_state=0
start_time = time()
trainset = construct_trainset(train_samples, reader.rating_scale)
algo = SVD(n_factors=10, n_epochs=10, biased=False, verbose=True)
#algo = SVDpp(n_factors=10, n_epochs=10, cache_ratings=True, verbose=True)
algo.fit(trainset)
print(f"Fitting time: {time()-start_time} seconds")

# start_time = time()
# # Then compute RMSE
# predictions = algo.test(raw_testset)
# accuracy.rmse(predictions)
# print(f"Testing time: {time()-start_time} seconds")

Processing epoch 0
Processing epoch 1
Processing epoch 2
Processing epoch 3
Processing epoch 4
Processing epoch 5
Processing epoch 6
Processing epoch 7
Processing epoch 8
Processing epoch 9
Fitting time: 81.11809062957764 seconds

In [21]:
start_time = time()
w_obs=LogisticMFProbs(random_state=random_state)
w_obs.fit(train_samples+calib_samples)
print(f"Elapsed time: {time()-start_time} seconds")

100%|████████████████████████████████████████████████████████████████████| 30/30 [00:21<00:00,  1.38it/s]

Elapsed time: 59.20809054374695 seconds

In [22]:
start_time = time()
k=5
Mhat = create_batch_rating_predictor(algo)
ci_method = SimulCI_ls(splitter.config, calib_samples, k, Mhat, w_obs, num_workers=6)
print(f"Elapsed time: {time()-start_time} seconds")

Elapsed time: 0.07295894622802734 seconds

In [23]:
calib_idxs = [(u, i) for u,i,r in calib_samples]
calib_ratings = [r for u,i,r in calib_samples]

In [25]:
start_time = time()
alpha = 0.1
allow_inf= False
df = ci_method.get_CI(calib_idxs, alpha, allow_inf=allow_inf)
print(f"Elapsed time: {time()-start_time} seconds")

Computing conformal prediction intervals for 2000 test queries...
Skipping some duplicated computations: w_test is unchanged.

CI: 100%|████████████████████████████████████████████████████████████| 2000/2000 [03:08<00:00, 10.60it/s]

Done!
Elapsed time: 188.75239872932434 seconds

In [26]:
lower, upper, is_inf, is_impossible = df.loc[0].lower, df.loc[0].upper, df.loc[0].is_inf, df.loc[0].is_impossible

In [27]:
def clip_intervals(lower, upper):
    lower[lower <= 1] = 1
    upper[upper >= 5] = 5
    return lower, upper

In [28]:
lower, upper = clip_intervals(lower, upper)

In [29]:
res = evaluate_SCI_ls(lower, upper, k, calib_ratings, is_inf, is_impossible)

Filtered out 0 impossible queries out of 2000 queries.
Evaluating 2000 queries...
Done!

In [30]:
res

   Query_coverage  Coverage      Size metric  Impossible_prop  Inf_prop
0           0.919    0.9817  3.648406   mean              0.0       0.0

In [31]:
test_idxs =  splitter.sample_test(k, max_n_test=200, random_state=0)

In [32]:
df = ci_method.get_CI(test_idxs, alpha, allow_inf=allow_inf)

Computing conformal prediction intervals for 200 test queries...
Skipping some duplicated computations: w_test is unchanged.

CI: 100%|██████████████████████████████████████████████████████████████| 200/200 [00:19<00:00, 10.39it/s]

Done!

In [33]:
lower, upper, is_inf, is_impossible = df.loc[0].lower, df.loc[0].upper, df.loc[0].is_inf, df.loc[0].is_impossible
lower, upper = clip_intervals(lower, upper)

In [34]:
res = evaluate_SCI_ls(lower, upper, k, np.zeros(len(test_idxs)), is_inf, is_impossible)

Filtered out 0 impossible queries out of 200 queries.
Evaluating 200 queries...
Done!

In [35]:
res

   Query_coverage  Coverage      Size metric  Impossible_prop  Inf_prop
0             0.0       0.0  3.688452   mean              0.0     0.025